# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4c3a6125b89cfa94918143cc65d4e7346232fcb2c52e17ad89bfeeea1ae9e3080d3b29d5a098898680c23989f384dcc7741355fdfdbf748aa6fd55daecc3d20

test:
  secret_key_base: 029534508c466f491a40744be8860c9383ac999dea4354fd69b8cdf911929ef169917c06c16743f7fae0df47c9584993730fbac47423b096b03d39bb619a2d8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
